FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# Build the scheduler binary
RUN CGO_ENABLED=0 go build -o scheduler ./cmd/scheduler

# Build the initializer binary
RUN CGO_ENABLED=0 go build -o init-weekly-evaluations ./cmd/init-weekly-evaluations

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/scheduler .
COPY --from=builder /app/init-weekly-evaluations .

CMD ["./scheduler"]
